development:
  adapter: postgresql
  database: bathshebas_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: bathshebas_test
  pool: 5
  timeout: 5000

production: 
  adapter: postgresql
  database: bathshebas_production
  pool: 5
  timeout: 5000
